### ISSUE TITLE
Apple Mach-O Linker (ld) Error Group

### ISSUE THREAD

**Issue by fukemy** [iOSDevLog/ijkplayer#5]
Hello. I got some error. dont know why. can u help :)

```

Showing All Issues
ld: warning: ignoring file /Users/macos/Downloads/ijkplayer-master/IJKMediaFramework.framework/IJKMediaFramework, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/macos/Downloads/ijkplayer-master/IJKMediaFramework.framework/IJKMediaFramework


```

![screen shot 2018-08-02 at 12 32 20](https://user-images.githubusercontent.com/8202437/43564270-32301c2e-9650-11e8-90cd-0be1fe2f747f.png)
![screen shot 2018-08-02 at 12 32 32](https://user-images.githubusercontent.com/8202437/43564279-3a909042-9650-11e8-9f53-991fab28d410.png)

**Comment by jiaxianhua** [comment]
I update ijkplayer version 0.8.8.
try the pods version :1.1.3.

**Comment by fukemy** [comment]
thanks you. Still see 1.1.2 in cocoapods. May be i need wait for some days more
